from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import EmailMessage
from django.conf import settings
from .models import Order

@receiver(post_save, sender=Order)
def send_notification_on_delivery(sender, instance, created, **kwargs):
    if instance.status == "Delivered" and not instance.notification_sent:
        email = EmailMessage(
            subject="Your Order Has Been Delivered 🥬",
            body=f"""
Hello {instance.customer.name},

Your order #{instance.id} has been delivered successfully.

Invoice is attached with this email.

Thank you for choosing FarmFresh.
""",
            from_email=settings.EMAIL_HOST_USER,
            to=[instance.customer.email]
        )

        # attach invoice (already generated by you)
        email.attach_file(instance.invoice.path)
        email.send()

        instance.notification_sent = True
        instance.save(update_fields=['notification_sent'])
