# Generated by Django 5.1.6 on 2026-01-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
